<script setup>
// Reference SHA-256: 91D03978BB5A413EBF79A2CDC25E00EABBF79499F65B672A267BFAB19596FB39
const types=[['overview-dataset.png','数据集','DATASET','数据源强集合管理'],['overview-report.png','报表展示','REPORT','报表设计与数据可视化'],['overview-rpa.png','RPA机器人','RPA','流程自动化与机器人应用'],['overview-ead.png','EAD应用','EAD','企业架构设计应用'],['overview-ai.png','AI智能体','AI_AGENT','AI智能交互与协同'],['overview-other.png','其他应用','OTHER','其他类型的应用']];
const domains=[['生产运营','RPA / 报表 / 数据集管理'],['市场营销','报表展示管理'],['物资采购','数据集管理'],['财务管理','报表展示/财务模型管理'],['人力资源','报表展示/系统集管理'],['安全环保','报表展示/数据集管理'],['工程建设','工程项目/工程数据管理'],['成本控制','工程项目/成本预算管理'],['综合管理','综合事务/办公运营管理']];
</script>
<template><article class="backend-page" aria-labelledby="backend-title"><nav>运营管理　/　后台管理</nav><header><h1 id="backend-title">后台管理</h1><p>管理应用开发、主题和权限分配等配置，保障平台稳定运行。</p></header><div class="config-grid"><section><h2>应用类型配置 <button>新增应用类型</button></h2><p>配置应用类型的图标、名称、排序及状态，支持新建、编辑与删除。</p><table><thead><tr><th>应用类型名称</th><th>类型说明/描述</th><th>排序</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="(item,index) in types" :key="item[1]"><td><AppIcon :name="item[0]" :size="42" />{{ item[1] }}</td><td>{{ item[2] }}<br/><small>{{ item[3] }}</small></td><td><input :value="index+1"/></td><td><label class="switch"><input type="checkbox" checked/>启用</label></td><td><a href="#main-content">编辑</a>　<a href="#main-content">删除</a></td></tr></tbody></table></section><section><h2>主题域配置 <button>新增主题域</button></h2><p>配置主题域的图标、名称、所属应用、排序及状态，支持新建、编辑与删除。</p><table><thead><tr><th>LOGO</th><th>主题域名称</th><th>所属应用/类型</th><th>排序</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="(item,index) in domains" :key="item[0]"><td><AppIcon :name="['overview-report','app-screen','app-metric','app-cockpit'][index%4]" :size="42" /></td><td>{{ item[0] }}</td><td>{{ item[1] }}</td><td><input :value="index+1"/></td><td><label class="switch"><input type="checkbox" checked/>启用</label></td><td><a href="#main-content">编辑</a>　<a href="#main-content">删除</a></td></tr></tbody></table></section></div><section class="log-panel"><h2>后台操作日志 <span>未处理告警 3</span></h2><p>记录到IAM平台相关的操作，包括修改及停用日志变更，便于追溯与管理。</p><table><thead><tr><th>时间</th><th>操作对象</th><th>操作类型</th><th>详情信息</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="(item,index) in ['/api/auth/login','/api/data/sync','/api/report/export','/api/file/upload','/api/user/info']" :key="item"><td>2025-06-01 09:{{ 45-index*4 }}:17</td><td>{{ item }}</td><td>{{ ['登录','同步','导出','上传','查询'][index] }}</td><td>受控本地 mock 操作记录 requestId=fx-817-{{ index }}</td><td>{{ index<2?'待处理':'已处理' }}</td><td><a href="#main-content">查看详情</a>　<a href="#main-content">处理记录</a></td></tr></tbody></table></section></article></template>
<style scoped>.backend-page{padding:15px 24px;color:#17304f}.backend-page>nav{font-size:10px}.backend-page h1{margin:10px 0 4px;font-size:24px}.backend-page header p,.config-grid section>p,.log-panel>p{font-size:10px}.config-grid{display:grid;grid-template-columns:1fr 1.15fr;gap:16px;margin-top:14px}.config-grid section,.log-panel{padding:16px;background:#fff;border:1px solid #dce5ef;border-radius:6px}.backend-page h2{margin:0;color:#0870e8;font-size:17px}.backend-page h2 button{float:right;padding:8px 18px;color:#fff;background:#0870e8;border:0}.backend-page table{width:100%;margin-top:12px;border-collapse:collapse;font-size:9px}.backend-page th,.backend-page td{height:39px;padding:0 8px;border-bottom:1px solid #e1e8ef;text-align:left}.backend-page th{background:#f5f7fa}.backend-page td img{display:inline-block;width:30px;height:30px;margin-right:10px;vertical-align:middle}.backend-page td input{width:40px}.backend-page td a{color:#0870e8}.log-panel{margin-top:14px}.log-panel h2 span{float:right;padding:7px;color:#e33;background:#fff0f0;font-size:10px}.log-panel td:nth-child(3){color:#f07820}.log-panel td:nth-child(5){color:#149252}button:focus-visible,a:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}@media(max-width:1000px){.config-grid{grid-template-columns:1fr}}
.backend-page :is(.config-grid section,.log-panel,th,td){border-color:#f4faff}
</style>
