<script setup>
// Reference SHA-256: 2A55B1987EA239C0D5FB184B7CAECF9F39FFB5AB7C505FB669746356A2820EC7
const metrics=[['最近更新日期','2025-06-08'],['应用类型','AI'],['所属业务域','智能办公'],['适用对象','集团内部员工'],['开发单位','信息化管理部'],['负责人','张三丰'],['所属部门','信息技术中心']];
const training=['长文总结智能体功能介绍','长文总结智能体使用入门','长文总结智能体高级技巧','长文总结智能体典型案例解析'];
</script>
<template>
  <article class="product-detail ai-detail" aria-labelledby="ai-title"><nav class="detail-crumb" aria-label="面包屑">应用中心　/　AI　/　应用详情</nav>
    <header class="detail-hero"><div class="detail-hero-main"><AppIcon class="detail-logo" name="ai-logo" :size="82" label="长文总结智能体图标" /><div class="detail-title"><h1 id="ai-title">长文总结智能体</h1><mark>AI</mark><mark>数智应用</mark><div class="detail-tags"><strong>自然语言处理：</strong><mark>文本摘要</mark><mark>智能问答</mark><mark>效率工具</mark><mark>知识提取</mark></div><p>应用URL地址：<b>本地受控演示</b></p></div><div class="detail-hero-side"><button type="button">申请使用</button><button type="button">收藏</button><button type="button">申请复用</button><img class="detail-illustration" src="/assets/ai-hero.png" width="205" height="105" alt="智能机器人插画" /></div></div><dl class="detail-metrics"><div v-for="([key,value],index) in metrics" :key="key"><b>{{ index+1 }}</b><dt>{{ key }}</dt><dd>{{ value }}</dd></div></dl></header>
    <section class="detail-panel"><h2>应用基本信息</h2><table class="ai-table"><tbody><tr><th>应用编码</th><td>AI-LANG-SUMMARY-001</td></tr><tr><th>应用类型</th><td>AI</td></tr><tr><th>应用简介</th><td>基于先进的自然语言处理技术，帮助用户快速提取长文本核心要点，生成结构化总结，提升信息处理效率。</td></tr><tr><th>所属业务域</th><td>智能办公</td></tr><tr><th>所属场景</th><td>知识管理、文档处理、会议纪要整理等</td></tr><tr><th>所属数据域</th><td>企业数据云—知识管理数据域</td></tr><tr><th>应用描述</th><td>用于长篇文档摘要、提炼、会议记录等文本的智能处理，支持多种格式文本输入。</td></tr></tbody></table></section>
    <section class="detail-panel"><h2>附件资料</h2><table class="file-list"><thead><tr><th>文件名称</th><th>文件大小</th><th>上传时间</th><th>上传人</th><th>操作</th></tr></thead><tbody><tr v-for="(name,index) in ['长文总结智能体使用手册.pdf','长文总结智能体配置示例.xlsx','长文总结智能体常见问题.docx']" :key="name"><td>{{ name }}</td><td>{{ 2.45-index*.7 }} MB</td><td>2025-06-08 10:32:10</td><td>张三丰</td><td><a href="#main-content">下载</a></td></tr></tbody></table></section>
    <section class="detail-panel"><h2>相关培训内容 <a href="/training">查看更多</a></h2><div class="training-row"><article v-for="(name,index) in training" :key="name"><img src="/assets/ai-training.png" alt="" :style="{objectPosition:`${index*33}% center`}" /><div><h3>{{ name }}</h3><p>时长：13:40</p></div></article></div></section>
    <section class="detail-panel"><h2>关联素材</h2><div class="related-row"><article v-for="(name,index) in ['通用行业知识图谱数据集','文本摘要RPA脚本','智能办公数据看板']" :key="name"><AppIcon :name="['dataset-logo','app-rpa','app-cockpit'][index]" :size="48" /><div><h3>{{ name }}</h3><p>{{ 1275+index*1065 }} 次下载</p></div></article></div></section>
    <form class="detail-comment" @submit.prevent><label>应用评论<input placeholder="请输入您对本应用的评论..." /></label><button type="submit">提交评论</button></form>
  </article>
</template>
<style scoped>.ai-detail .detail-hero{min-height:230px}.ai-table{width:100%;border-collapse:collapse;font-size:10px}.ai-table th,.ai-table td{height:24px;padding:4px 12px;border:1px solid #dce5ef;text-align:left}.ai-table th{width:160px;background:#f3f6fa}.ai-detail .training-row img{width:75px;height:56px}button:focus-visible,a:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}</style>
