<script setup>
// Reference SHA-256: 5ADAECAADC46CCC242A570AEE5037A045FCECF39CBDA7D091283CE288DF9BE4F
import { ref } from 'vue';
const props=defineProps({operationExecutor:{type:Function,default:null}});
const title=ref('数智展厅 V2.0 新应用上线通知');
const content=ref(`数智展厅 V2.0 全新升级，多款应用重磅上线！

为进一步提升业务数字化能力，优化用户体验，数智展厅 V2.0 版本正式发布，新增多款应用并持续优化功能，助力各单位高效协同、智能决策。

本次更新亮点
1. 新增智能报表、数据画像等 8 款应用，覆盖更多业务场景
2. 优化应用体验与权限管理，提升系统稳定性与安全性
3. 支持多端展示与符合单点登录与组织架构同步`);
const preview=ref(null);
const previewState=ref('idle');
async function requestPreview(){
  if(!props.operationExecutor){previewState.value='unavailable';return;}
  previewState.value='loading';
  try{
    const response=await props.operationExecutor('OAN-008',{title:title.value,contentHtml:`<p>${content.value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('\n','<br>')}</p>`,previewMode:'DESKTOP'});
    preview.value=response?.data||null;
    previewState.value='normal';
  }catch(error){previewState.value=error?.code==='AUTHENTICATION_REQUIRED'?'authentication-required':'error';}
}
function closePreview(){preview.value=null;previewState.value='idle';}
</script>
<template><article class="editor-page" aria-labelledby="announcement-editor-title"><p class="sr-only" aria-live="polite">{{ previewState==='loading'?'正在生成公告预览':previewState==='error'?'公告预览生成失败':'' }}</p><nav>运营管理　/　公告管理</nav><header><h1 id="announcement-editor-title">公告发布与编辑</h1><p>发布公告通知，支持全平台或指定范围的组织与用户接收。</p></header><form @submit.prevent><section><h2><span>1</span> 基本信息</h2><div class="basic-grid"><label>公告标题 *<input v-model="title"/></label><fieldset><legend>公告类型 *</legend><label><input type="radio" checked/>新应用上线</label><label><input type="radio"/>活动通知</label><label><input type="radio"/>平台通知</label></fieldset><label>发布时间 *<input value="2025-06-08 10:18"/></label><label>有效期 *<input value="2025-06-08 00:00　~　2025-07-08 23:59"/></label></div></section><section><h2><span>2</span> 公告正文 *</h2><textarea v-model="content" rows="10"></textarea><small>共 {{ content.length }} 字</small></section><div class="editor-split"><section><h2><span>3</span> 附件上传（选填）</h2><button type="button" class="upload">点击上传<br/><small>或拖拽文件到此处</small></button><ul><li>数智展厅 V2.0 新功能说明.docx　1.25 MB</li><li>应用上线操作指南.pdf　2.18 MB</li></ul></section><section><h2><span>4</span> 关联对象（选填）</h2><p>关联后可在应用详情页展示该公告</p><div class="selected">智能报表系统　×</div><button type="button" class="choose">选择应用</button></section></div><footer><button type="button">保存草稿</button><button type="button" :disabled="previewState==='loading'" @click="requestPreview">{{ previewState==='loading'?'生成中…':'预览' }}</button><button type="submit">发布</button><button type="reset">取消</button></footer></form><div v-if="preview" class="preview-backdrop" role="presentation" @click.self="closePreview"><section class="preview-dialog" role="dialog" aria-modal="true" aria-labelledby="preview-title"><header><h2 id="preview-title">{{ title }}</h2><button type="button" aria-label="关闭预览" @click="closePreview">×</button></header><div class="preview-content" v-html="preview.sanitizedContentHtml"></div><p v-if="preview.warnings.length" class="preview-warning">{{ preview.warnings.map(item=>item.message).join('；') }}</p></section></div></article></template>
<style scoped>.editor-page{padding:20px 35px;color:#17304f}.editor-page>nav{font-size:11px}.editor-page h1{margin:12px 0 4px;font-size:24px}.editor-page header p{font-size:11px}.editor-page form>section,.editor-split>section{margin-top:18px;padding:18px;background:#fff;border:1px solid #dce5ef;border-radius:6px}.editor-page h2{margin:0 0 20px;color:#0870e8;font-size:15px}.editor-page h2 span{display:inline-grid;place-items:center;width:18px;height:18px;color:#fff;background:#0870e8;border-radius:50%;font-size:10px}.basic-grid{display:grid;grid-template-columns:1.2fr 1.2fr 1fr 1.4fr;gap:25px}.basic-grid>label,.basic-grid fieldset{display:grid;gap:10px;margin:0;padding:0;border:0;font-size:11px}.basic-grid input,.editor-page textarea{padding:10px;border:1px solid #d8e2ec;border-radius:4px}.basic-grid fieldset{display:flex;align-items:end}.basic-grid legend{position:absolute}.editor-page textarea{width:100%;resize:none;line-height:2}.editor-page form>section>small{float:right}.editor-split{display:grid;grid-template-columns:1fr 1fr;gap:18px}.upload{width:100%;height:75px;color:#17304f;background:#fff;border:1px dashed #a9c8ef}.editor-page ul{list-style:none;padding:0;font-size:10px}.selected{padding:12px;background:#f7f9fc;border:1px solid #dce5ef}.choose{width:100%;height:38px;color:#0870e8;background:#fff;border:1px solid #dce5ef}.editor-page form>footer{display:flex;justify-content:center;gap:30px;padding:20px}.editor-page footer button{height:38px;min-width:140px;color:#0870e8;background:#fff;border:1px solid #0870e8}.editor-page footer button[type=submit]{color:#fff;background:#0870e8}.preview-backdrop{position:fixed;inset:0;z-index:80;display:grid;place-items:center;padding:32px;background:rgb(9 37 75 / 45%)}.preview-dialog{width:min(720px,90vw);max-height:80vh;overflow:auto;padding:28px;background:#fff;border-radius:10px;box-shadow:0 22px 65px rgb(9 37 75 / 25%)}.preview-dialog>header{display:flex;align-items:center;justify-content:space-between;gap:24px;border-bottom:1px solid #dce5ef}.preview-dialog h2{margin:0 0 16px;color:#17304f;font-size:22px}.preview-dialog header button{width:38px;height:38px;border:0;background:transparent;color:#617895;font-size:28px}.preview-content{padding:24px 0;color:#213b5c;line-height:1.9}.preview-warning{padding:10px;color:#9b5b00;background:#fff5df;border-radius:4px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}button:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}@media(max-width:900px){.basic-grid,.editor-split{grid-template-columns:1fr 1fr}}
</style>
