<script setup>
// Reference SHA-256: 07B0623CB569C7829B490B85A65007D2773C4AE2ADB3ADE4B6089279F3D248FB
import { computed } from 'vue';
import { resolvePage } from '../fixtures/pages.js';
const props=defineProps({integrationData:{type:Object,default:null},integrationState:{type:String,default:'loading'},operationExecutor:{type:Function,default:null}});
const summary=computed(()=>props.integrationData?.['OAN-001']||{});const list=computed(()=>props.integrationData?.['OAN-002']||{});
const state=computed(()=>{if(props.integrationState==='loading')return'loading';if(['authentication-required','permission-denied'].includes(props.integrationState))return'permission-denied';if(['error','timeout','rate-limited','schema-drift','security-error'].includes(props.integrationState))return'error';if(props.integrationState==='empty')return'empty';return Array.isArray(list.value.items)&&list.value.items.length?'normal':'empty';});
const stats=computed(()=>[['公告总数',scalar(summary.value,'totalCount','total')],['已发布',scalar(summary.value,'publishedCount')],['草稿',scalar(summary.value,'draftCount')],['已过期',scalar(summary.value,'expiredCount')]]);
const rows=computed(()=>(list.value.items||[]).map((item,index)=>({id:item.announcementId||item.id||`announcement-${index}`,title:item.title||item.name||'—',type:item.typeName||item.typeCode||'—',time:item.publishAt||item.updatedAt||'—',scope:item.scopeName||item.scopeType||'—',status:item.statusName||item.statusCode||item.status||'—',views:item.viewCount??item.readCount??'—',route:safeRoute(item.detailPath||item.path)})));
const total=computed(()=>(list.value.total??rows.value.length));const page=computed(()=>(list.value.page??1));
function scalar(object,...keys){for(const key of keys)if(['string','number','boolean'].includes(typeof object?.[key]))return String(object[key]);return'—';}
function safeRoute(path){if(!path)return'';try{const url=new URL(path,window.location.origin);return url.origin===window.location.origin&&resolvePage(url.href,'normal')?`${url.pathname}${url.search}${url.hash}`:'';}catch{return'';}}
</script>
<template><article class="admin-list" aria-labelledby="notice-admin-title" :data-state="state"><nav>运营管理　/　公告管理</nav><header><div><h1 id="notice-admin-title">公告管理</h1><p>发布、管理平台公告，支持新应用上线、活动通知、平台通知三种类型，及时触达用户。</p></div><button type="button" disabled title="正式公告写合同尚未开放">新建公告</button></header><section v-if="state!=='normal'" class="admin-state" :role="state==='error'||state==='permission-denied'?'alert':'status'">{{ state==='loading'?'正在加载公告运营数据…':state==='permission-denied'?'当前身份无权查看公告运营数据。':state==='error'?'公告运营数据暂不可用。':'当前没有公告运营记录。' }}</section><template v-else><section class="admin-stats"><article v-for="(stat,index) in stats" :key="stat[0]"><AppIcon :name="['notice-stat-unread','points-month','points-use','points-total'][index]" :size="58"/><div><small>{{ stat[0] }}</small><strong>{{ stat[1] }}</strong></div></article></section><form @submit.prevent><label>公告类型<select><option>全部</option></select></label><label>标题关键词<input placeholder="请输入公告标题关键词"/></label><label>状态<select><option>全部</option></select></label><label>发布时间<input placeholder="开始日期　~　结束日期"/></label><label>发布范围<select><option>全部</option></select></label><button type="reset">重置</button><button type="submit">查询</button></form><p v-if="list.filtersApplied" class="applied-filters">服务端已应用筛选条件</p><section class="admin-table"><table><caption class="sr-only">公告运营列表</caption><thead><tr><th scope="col">标题</th><th scope="col">类型</th><th scope="col">发布时间</th><th scope="col">发布范围</th><th scope="col">状态</th><th scope="col">浏览量</th><th scope="col">置顶</th><th scope="col">操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{ row.title }}</td><td><mark>{{ row.type }}</mark></td><td>{{ row.time }}</td><td>{{ row.scope }}</td><td><span>{{ row.status }}</span></td><td>{{ row.views }}</td><td>—</td><td><a v-if="row.route" :href="row.route">预览</a><button type="button" disabled>编辑</button><button type="button" disabled>下线</button><button type="button" disabled>删除</button></td></tr></tbody></table><footer>共 {{ total }} 条 <nav aria-label="分页"><button disabled>上一页</button><button aria-current="page">{{ page }}</button><button disabled>下一页</button></nav></footer></section></template></article></template>
<style scoped>.admin-list{padding:18px 24px;color:#17304f}.admin-list>nav{font-size:11px}.admin-list>header{display:flex;justify-content:space-between}.admin-list h1{margin:12px 0 5px;font-size:24px}.admin-list header p{font-size:11px}.admin-list header>a{height:42px;padding:12px 24px;color:#fff;background:#0060a6;border-radius:4px}.admin-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}.admin-stats article{height:115px;display:flex;align-items:center;gap:22px;padding:18px;background:#fff;border:1px solid #dce5ef;border-radius:6px}.admin-stats img{width:70px;height:70px}.admin-stats strong{display:block;font-size:26px}.admin-stats p{color:#13a45d;font-size:10px}.admin-list>form{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;padding:17px;background:#fff;border:1px solid #dce5ef}.admin-list form label{display:flex;align-items:center;gap:10px;font-size:11px}.admin-list input,.admin-list select{height:35px;min-width:0;flex:1;border:1px solid #d8e2ec}.admin-list form button{height:35px;color:#0060a6;background:#fff;border:1px solid #0060a6}.admin-list form button:last-child{color:#fff;background:#0060a6}.admin-table{margin-top:12px;background:#fff;border:1px solid #dce5ef}.admin-table table{width:100%;border-collapse:collapse;font-size:9px}.admin-table th,.admin-table td{height:45px;padding:0 12px;border-bottom:1px solid #e1e8ef;text-align:left}.admin-table th{background:#f5f7fa}.admin-table mark{color:#0060a6;background:#e9f3ff}.admin-table td span{color:#159354;background:#e9f8ef}.admin-table td a{color:#0060a6}.admin-table td button{color:#e33;border:0;background:transparent}.admin-table footer{display:flex;justify-content:space-between;padding:16px}.admin-table footer button{height:30px;border:1px solid #d8e2ec;background:#fff}.admin-table footer button[aria-current=page]{color:#fff;background:#0060a6}button:focus-visible,a:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}
.admin-list{padding:24px}.admin-list>nav{min-height:32px;display:flex;align-items:center;font-size:14px;line-height:1.5}.admin-list>header{min-height:104px;align-items:flex-start;gap:24px;padding:14px 0 20px}.admin-list h1{margin:0 0 8px;font-size:30px;line-height:1.35}.admin-list header p{margin:0;font-size:15px;line-height:1.65}.admin-list header>a{min-width:112px;height:42px;display:inline-flex;align-items:center;justify-content:center;padding:0 22px;font-size:14px;white-space:nowrap}.admin-stats{margin:0 0 16px}.admin-stats article{min-height:112px;height:auto}.admin-stats strong{line-height:1.3}.admin-stats p{margin:4px 0 0;font-size:13px}.admin-list>form{grid-template-columns:minmax(140px,.75fr) minmax(210px,1.25fr) minmax(140px,.75fr) minmax(210px,1.1fr) minmax(140px,.75fr) 70px 70px;align-items:center;gap:10px;padding:14px 16px;border-radius:6px}.admin-list form label{min-width:0;gap:8px;font-size:14px;line-height:1.5;white-space:nowrap}.admin-list input,.admin-list select{height:38px;padding:0 10px;font-size:14px}.admin-list form button{height:38px;border-radius:4px;font-size:14px}.admin-table{margin-top:14px}.admin-table table{font-size:13px}.admin-table th,.admin-table td{height:48px;padding:8px 12px;line-height:1.5}.admin-table footer{align-items:center;font-size:13px}.admin-table footer button{height:32px;padding:0 10px}
@media(max-width:1500px){.admin-list>form{grid-template-columns:repeat(2,minmax(0,1fr))}.admin-list>form button{width:100%}}
@media(max-width:760px){.admin-list{padding:12px}.admin-list>header{flex-direction:column}.admin-list>form{grid-template-columns:1fr}.admin-stats{grid-template-columns:1fr}}
.admin-list>header>button{height:42px;padding:0 22px}.admin-state{min-height:320px;display:grid;place-items:center;background:#fff;border:1px solid #dce5ef;border-radius:6px}.applied-filters{color:#61758b;font-size:12px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.admin-table td button{margin-left:8px}
</style>
