<script setup>
// Reference SHA-256: D3996593EAF90E612EA8874CDD41283565876ACDA3A9BD774343C0C469903795
import { computed } from 'vue';
import { resolvePage } from '../fixtures/pages.js';
const props=defineProps({integrationData:{type:Object,default:null},integrationState:{type:String,default:'loading'},operationExecutor:{type:Function,default:null}});
const summary=computed(()=>props.integrationData?.['OAP-001']||{});const list=computed(()=>props.integrationData?.['OAP-002']||{});const exportSummary=computed(()=>props.integrationData?.['OAP-011']||null);
const state=computed(()=>{if(props.integrationState==='loading')return'loading';if(['authentication-required','permission-denied'].includes(props.integrationState))return'permission-denied';if(['error','timeout','rate-limited','schema-drift','security-error'].includes(props.integrationState))return'error';if(props.integrationState==='empty')return'empty';return Array.isArray(list.value.items)&&list.value.items.length?'normal':'empty';});
const stats=computed(()=>[['应用总数',scalar(summary.value,'totalCount','total')],['已上架',scalar(summary.value,'onlineCount','publishedCount')],['已下架',scalar(summary.value,'offlineCount')],['待审核',scalar(summary.value,'pendingCount','reviewCount')]]);
const rows=computed(()=>(list.value.items||[]).map((item,index)=>({id:item.appId||item.applicationId||item.id||`application-${index}`,values:[item.name||item.title||'—',item.code||item.appCode||'—',item.typeName||item.typeCode||'—',item.domainName||item.domainCode||'—',item.ownerName||item.managerName||'—',item.viewCount??item.visitCount??'—',item.userCount??item.useCount??'—',item.statusName||item.statusCode||item.status||'—',item.recommendStatusName||item.recommendStatus||'—',item.hotStatusName||item.hotStatus||'—',item.updatedAt||item.publishAt||'—'],route:safeRoute(item.detailPath||item.path)})));
const total=computed(()=>(list.value.total??rows.value.length));const page=computed(()=>(list.value.page??1));
const exportFields=computed(()=>{if(!exportSummary.value)return[];return Object.entries(exportSummary.value).filter(([,value])=>['string','number','boolean'].includes(typeof value)).slice(0,6);});
function scalar(object,...keys){for(const key of keys)if(['string','number','boolean'].includes(typeof object?.[key]))return String(object[key]);return'—';}
function safeRoute(path){if(!path)return'';try{const url=new URL(path,window.location.origin);return url.origin===window.location.origin&&resolvePage(url.href,'normal')?`${url.pathname}${url.search}${url.hash}`:'';}catch{return'';}}
</script>
<template><article class="app-admin" aria-labelledby="app-admin-title" :data-state="state"><nav>运营管理　/　应用管理</nav><header><div><h1 id="app-admin-title">应用运营管理</h1><p>对已上架的应用进行运营管理，包括状态查看、数据监控、推荐配置等。</p></div><button type="button" disabled title="正式应用写合同尚未开放">新建应用</button></header><section v-if="state!=='normal'" class="app-admin-state" :role="state==='error'||state==='permission-denied'?'alert':'status'">{{ state==='loading'?'正在加载应用运营数据…':state==='permission-denied'?'当前身份无权查看应用运营数据。':state==='error'?'应用运营数据暂不可用。':'当前没有应用运营记录。' }}</section><template v-else><section class="app-admin-stats"><article v-for="(item,index) in stats" :key="item[0]"><AppIcon :name="['overview-ead','points-month','points-use','points-total'][index]" :size="58"/><div><small>{{ item[0] }}</small><strong>{{ item[1] }}</strong></div></article></section><form @submit.prevent><label>应用名称/编码<input placeholder="请输入应用名称/编码"/></label><label>应用类型<select><option>全部</option></select></label><label>主题域<select><option>全部</option></select></label><label>状态<select><option>全部</option></select></label><label>负责人<input placeholder="请输入负责人"/></label><label>时间范围<input placeholder="开始日期　~　结束日期"/></label><button type="reset">重置</button><button type="submit">查询</button></form><p v-if="list.filtersApplied" class="applied-filters">服务端已应用筛选条件</p><dl v-if="exportFields.length" class="export-summary"><div v-for="([key,value]) in exportFields" :key="key"><dt>{{ key }}</dt><dd>{{ value }}</dd></div></dl><section class="app-admin-table"><table><caption class="sr-only">应用运营列表</caption><thead><tr><th v-for="heading in ['应用名称','编码','类型','主题域','负责人','访问量','使用人数','状态','推荐状态','热门状态','更新时间','操作']" :key="heading" scope="col">{{ heading }}</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td v-for="(value,index) in row.values" :key="index">{{ value }}</td><td><a v-if="row.route" :href="row.route">查看</a><button type="button" disabled>编辑</button><button type="button" disabled>推荐</button><button type="button" disabled>下线</button></td></tr></tbody></table><footer>共 {{ total }} 条 <nav aria-label="分页"><button disabled>上一页</button><button aria-current="page">{{ page }}</button><button disabled>下一页</button></nav></footer></section></template></article></template>
<style scoped>.app-admin{padding:20px 24px;color:#17304f}.app-admin>nav{font-size:11px}.app-admin>header{display:flex;justify-content:space-between}.app-admin h1{margin:10px 0 4px;font-size:24px}.app-admin header p{font-size:11px}.app-admin header>a{height:42px;padding:12px 24px;color:#fff;background:#0060a6}.app-admin-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:18px 0}.app-admin-stats article{height:115px;display:flex;align-items:center;gap:20px;padding:17px;background:#fff;border:1px solid #dce5ef}.app-admin-stats img{width:70px;height:70px}.app-admin-stats strong{display:block;font-size:25px}.app-admin-stats p{color:#13a45d;font-size:10px}.app-admin>form{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;padding:16px;background:#fff;border:1px solid #dce5ef}.app-admin form label{display:flex;align-items:center;gap:8px;font-size:10px}.app-admin input,.app-admin select{height:34px;min-width:0;flex:1;border:1px solid #d8e2ec}.app-admin form button{height:34px;color:#0060a6;background:#fff;border:1px solid #0060a6}.app-admin form button:last-child{color:#fff;background:#0060a6}.app-admin-table{margin-top:10px;overflow:auto;background:#fff;border:1px solid #dce5ef}.app-admin table{width:100%;min-width:1200px;border-collapse:collapse;font-size:9px}.app-admin th,.app-admin td{height:39px;padding:0 10px;border-bottom:1px solid #e1e8ef;text-align:left}.app-admin th{background:#f5f7fa}.app-admin td a{color:#0060a6}.app-admin td button{color:#e33;border:0;background:transparent}.app-admin-table footer{display:flex;justify-content:space-between;padding:14px}.app-admin-table footer button{height:30px;border:1px solid #d8e2ec;background:#fff}.app-admin-table footer button[aria-current=page]{color:#fff;background:#0060a6}button:focus-visible,a:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}
.app-admin{padding:31px 33px 20px 19px}.app-admin-stats{margin:24px 0 15px}.app-admin header>a{margin-top:12px}
.app-admin>header>button{height:42px;margin-top:12px;padding:0 22px}.app-admin-state{min-height:320px;display:grid;place-items:center;background:#fff;border:1px solid #dce5ef}.app-admin td button{margin-left:8px}.applied-filters{color:#61758b;font-size:12px}.export-summary{display:flex;gap:18px;flex-wrap:wrap;padding:10px 14px;background:#f5f8fb}.export-summary div{display:flex;gap:6px}.export-summary dd{margin:0}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
</style>
