<script setup>
// Reference SHA-256: E11BA453D013006EE96D19695AC3770A794DEF4DB32B71D993A4158F7BC23ADD
const apps = [
  ['app-rpa.png','招投标发票查验机器人','RPA','财务管理','自动识别并查验招投标发票，提升审核效率','1,542','812','财务共享中心','李娜'],
  ['app-screen.png','供应商评估大屏','大屏','供应链管理','多维展示供应商绩效、质量与风险预警','2,378','1,128','供应链管理部','王建国'],
  ['app-cockpit.png','生产经营驾驶舱','驾驶舱','生产运营','汇总生产经营指标，支持管理决策与态势研判','1,986','967','生产运营部','张伟'],
  ['app-metric.png','物资供应链指标库','指标','供应链管理','统一沉淀物资供应链核心指标及统计口径','1,326','678','物资管理部','刘洋'],
  ['app-dataset.png','采购运营数据集','数据集','采购管理','汇聚采购订单、供应商及履约主题数据','1,198','543','采购管理部','王芳'],
  ['app-ai.png','智能采购助手','AI','采购管理','智能推荐、需求匹配，辅助采购决策','1,724','1,023','采购管理部','王芳'],
  ['app-work.png','海能work协同办公','海能work应用','综合管理','集成移动办公、任务协同与知识管理','2,865','1,456','综合管理部','张三丰']
];
</script>

<template>
  <article class="apps-page" aria-labelledby="apps-title">
    <header><div><h1 id="apps-title">应用中心</h1><p>汇聚优质应用资源，助力业务高效协同与智能决策</p></div><button type="button">应用上线申请</button></header>
    <form class="apps-filter" aria-label="应用筛选" @submit.prevent><label>应用名称或关键词<input type="search" placeholder="请输入应用名称或关键词" /></label><label>标签<select><option>请选择标签</option></select></label><label>应用类型<select><option>请选择应用类型</option></select></label><label>主题域<select><option>请选择主题域</option></select></label><button type="reset">重置</button><button type="submit">查询</button></form>
    <div class="apps-tools"><strong>全部应用 7 个</strong><button type="button">清空筛选</button><select aria-label="排序"><option>综合排序</option></select><button type="button" aria-label="卡片视图">卡片</button><button type="button" aria-label="列表视图">列表</button></div>
    <section class="apps-grid" aria-label="应用列表"><article v-for="(app,index) in apps" :key="app[1]"><header><img :src="`/assets/${app[0]}`" width="58" height="58" alt="" /><div><h2>{{ app[1] }}</h2><mark>{{ app[2] }}</mark><mark>{{ app[3] }}</mark></div></header><p>{{ app[4] }}</p><dl><div><dt>使用量</dt><dd>{{ app[5] }}</dd></div><div><dt>收藏</dt><dd>{{ app[6] }}</dd></div><div><dt>所属部门</dt><dd>{{ app[7] }}</dd></div><div><dt>负责人</dt><dd>{{ app[8] }}</dd></div><div><dt>开发部门/单位</dt><dd>{{ index % 2 ? '数据管理中心' : '自动化开发组' }}</dd></div><div><dt>开发者</dt><dd>{{ index % 2 ? '李明' : '周凯' }}</dd></div></dl><footer><a :href="index === 3 ? '/apps/metric-001' : index === 4 ? '/apps/dataset-001' : index === 5 ? '/apps/ai-001' : index === 6 ? '/apps/haineng-work-001' : '/apps/tool-001'">查看详情</a><button type="button">立即使用</button><button type="button">收藏</button><button type="button">申请复用</button></footer></article></section>
    <footer class="apps-pagination"><strong>共 7 条</strong><button type="button" aria-current="page">1</button><label>每页<select><option>12条/页</option></select></label><label>跳至<input value="1" />页</label></footer>
  </article>
</template>

<style scoped>
.apps-page{padding:18px 27px;color:#183150}.apps-page>header{display:flex;justify-content:space-between}.apps-page h1{margin:0;font-size:24px}.apps-page>header p{margin-top:5px;color:#60718a;font-size:12px}.apps-page>header button,.apps-filter button,.apps-grid footer button{color:#fff;background:#086fe8;border:1px solid #086fe8;border-radius:4px}.apps-page>header button{height:35px;padding:0 19px}.apps-filter{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr auto auto;align-items:end;gap:24px;margin-top:22px}.apps-filter label{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:12px;font-size:12px;font-weight:700}.apps-filter input,.apps-filter select{height:36px;padding:0 12px;border:1px solid #d8e2ec;border-radius:4px;background:#fff;font-size:11px}.apps-filter button{height:36px;padding:0 22px}.apps-filter button[type=reset]{color:#086fe8;background:#fff}.apps-tools{display:flex;align-items:center;gap:14px;margin:25px 0 9px}.apps-tools>button{border:0;color:#086ce7;background:transparent}.apps-tools select{width:145px;height:34px;margin-left:auto;border:1px solid #d9e2ec}.apps-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px 18px}.apps-grid>article{min-height:210px;padding:15px 18px 9px;background:#fff;border:1px solid #dce5ef;border-radius:7px}.apps-grid article>header{display:flex;gap:17px}.apps-grid h2{margin:3px 0 8px;color:#192840;font-size:17px}.apps-grid mark{margin-right:8px;padding:3px 6px;color:#0870e8;background:#e9f3ff;font-size:9px}.apps-grid article>p{margin:10px 0;color:#53687f;font-size:11px}.apps-grid dl{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:0}.apps-grid dl div{display:flex;gap:8px;font-size:10px}.apps-grid dt{color:#62758a}.apps-grid dd{margin:0;color:#1c3150;font-weight:700}.apps-grid footer{display:flex;gap:8px;margin-top:10px}.apps-grid footer a,.apps-grid footer button{height:28px;display:grid;place-items:center;padding:0 13px;font-size:10px}.apps-grid footer a{color:#0870e8;border:1px solid #91bbf4;border-radius:4px}.apps-grid footer button:nth-of-type(n+2){color:#26405f;background:#fff;border-color:transparent}.apps-pagination{display:flex;align-items:center;gap:42px;padding:15px 8px}.apps-pagination>button{width:44px;height:34px;margin-left:auto;color:#0870e8;background:#fff;border:1px solid #0870e8}.apps-pagination label{display:flex;gap:8px;align-items:center;font-size:11px}.apps-pagination select,.apps-pagination input{height:34px;border:1px solid #dae3ec;background:#fff}.apps-pagination input{width:45px;text-align:center}button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}@media(max-width:1050px){.apps-grid{grid-template-columns:repeat(2,1fr)}.apps-filter{grid-template-columns:repeat(2,1fr)}}@media(max-width:700px){.apps-grid,.apps-filter{grid-template-columns:1fr}.apps-page{padding:12px}}
</style>
