<script setup>
// Reference SHA-256: 7260427E1B5E85ECDFE37D52D6A88439178542503EC8E5E6FC5D679701633C97
const metrics=[['启用时间','3,562 次'],['应用使用','2,418 次'],['最近发布时间','2025-05-06'],['开发单位','数据智能部'],['运营人员','李四强'],['所属部门','数据智能部'],['开发者','王建国']];
const fields=[['供应商编码','supplier_id','字符串'],['供应商名称','supplier_name','字符串'],['统一社会信用代码','credit_code','字符串'],['企业类型','enterprise_type','字符串'],['注册资本(万元)','registered_capital','数值'],['成立日期','establish_date','日期'],['联系人姓名','contact_name','字符串'],['联系电话','contact_phone','字符串'],['供应商分类','supplier_category','字符串'],['供应商等级','supplier_level','字符串']];
</script>
<template>
  <article class="product-detail dataset-detail" aria-labelledby="dataset-title"><nav class="detail-crumb" aria-label="面包屑">应用中心　/　数据集　/　应用详情</nav>
    <header class="detail-hero"><div class="detail-hero-main"><img class="detail-logo" src="/assets/dataset-logo.png" width="56" height="56" alt="供应商基础信息数据集图标" /><div class="detail-title"><h1 id="dataset-title">供应商基础信息数据集</h1><mark>数据集</mark><mark>供应商管理</mark><p>汇聚供应商注册、资质、分类、评价及合作历史等基础信息，提供标准化的供应商主数据服务。</p><div class="detail-tags"><strong>应用关键词</strong><mark>供应商主数据</mark><mark>采购管理</mark><mark>资质管理</mark><mark>风险监控</mark><mark>数据分析</mark></div></div><div class="detail-hero-side"><button type="button">收藏</button><button type="button">申请使用</button><button type="button">申请复用</button><img class="detail-illustration" src="/assets/dataset-hero.png" width="185" height="145" alt="供应商数据服务插画" /></div></div><dl class="detail-metrics"><div v-for="([key,value],index) in metrics" :key="key"><b>{{ index+1 }}</b><dt>{{ key }}</dt><dd>{{ value }}</dd></div></dl></header>
    <section class="detail-panel"><h2>应用基本信息</h2><dl class="info-grid"><div class="wide"><dt>应用编码</dt><dd>供应商基础信息数据集整合了集团及各单位所属的各级单位与下属信息，提供接口获取服务采用。</dd></div><div><dt>适用对象</dt><dd>采购人员、供应商管理人员、风险人员、数据分析人员</dd></div><div><dt>所属领域</dt><dd>供应商管理</dd></div><div><dt>应用场景</dt><dd>供应商注册与准入、采购寻源与比价、供应商绩效评价、风险监控与预警</dd></div><div><dt>更新频率</dt><dd>T+1 增量更新，关键字段实时同步</dd></div></dl></section>
    <section class="detail-panel"><h2>数据列表 <a href="#main-content">查看全部字段（12）</a></h2><table class="file-list"><thead><tr><th>字段名称</th><th>字段标识</th><th>数据类型</th></tr></thead><tbody><tr v-for="field in fields" :key="field[1]"><td>{{ field[0] }}</td><td>{{ field[1] }}</td><td>{{ field[2] }}</td></tr></tbody></table><a class="more" href="#main-content">查看更多数据列表</a></section>
    <section class="detail-panel"><h2>附件资料</h2><table class="file-list"><thead><tr><th>文件名称</th><th>文件大小</th><th>上传时间</th><th>上传人</th><th>操作</th></tr></thead><tbody><tr v-for="(name,index) in ['供应商基础信息数据模板.xlsx','供应商基础信息数据集-样例数据.csv','供应商基础信息数据集-画像关系图.png']" :key="name"><td>{{ name }}</td><td>{{ 856+index*220 }} KB</td><td>2025-05-06 10:{{ 32+index }}:10</td><td>张三丰</td><td><a href="#main-content">下载</a></td></tr></tbody></table></section>
    <section class="detail-panel"><h2>相关培训内容</h2><img class="preview-wide dataset-training" src="/assets/dataset-training.png" width="410" height="140" alt="供应商数据集培训视频封面" /></section>
    <section class="detail-panel"><h2>关联素材</h2><div class="related-row"><article v-for="(name,index) in ['供应商资质审核规则库','采购风控RPA脚本','供应商数据分析大屏']" :key="name"><img :src="['/assets/dataset-logo.png','/assets/app-rpa.png','/assets/app-cockpit.png'][index]" alt="" /><div><h3>{{ name }}</h3><p>{{ 1680+index*725 }} 次下载</p></div></article></div></section>
    <form class="detail-comment" @submit.prevent><label>应用评论<input placeholder="请输入您对该应用的评论..." /></label><button type="submit">提交评论</button></form>
  </article>
</template>
<style scoped>.dataset-detail .detail-hero{min-height:235px}.dataset-detail .detail-logo{width:56px;height:56px}.wide{grid-column:1/-1}.dataset-training{max-width:820px}.more{display:block;padding:12px;text-align:center;color:#0870e8;font-size:10px}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}</style>
