<script setup>
// Reference SHA-256: 21D2FCC06638F323E7824176C53BB72DDE1050790E6B4E457D54CD2D7398431C
const metrics=[['创建日期','2025-09-08'],['应用类型','应用'],['所属业务域','数字化办公'],['开发单位','信息化管理部'],['负责人','张三丰'],['所属部门','物资采购中心'],['开发者','李四']];
</script>
<template>
  <article class="product-detail work-detail" aria-labelledby="work-title"><nav class="detail-crumb" aria-label="面包屑">我的应用　/　应用中心　/　应用详情</nav>
    <header class="detail-hero"><div class="detail-hero-main"><img class="detail-logo" src="/assets/work-logo.png" width="70" height="70" alt="海能work应用图标" /><div class="detail-title"><h1 id="work-title">海能work应用</h1><mark>应用</mark><mark>数字化办公</mark><mark>已上线</mark><p>集成海油核心业务应用，统一工作门户，提升协同效率，赋能数字化办公新体验。</p><p>应用URL地址：<b>本地受控演示</b></p><div class="detail-tags"><strong>应用关键词</strong><mark>协同办公</mark><mark>企业门户</mark><mark>多租户</mark><mark>流程审批</mark><mark>移动办公</mark></div></div><div class="detail-hero-side"><button type="button">收藏</button><button type="button">立即使用</button><button type="button">申请复用</button><img class="detail-illustration" src="/assets/work-hero.png" width="250" height="135" alt="海能work应用插画" /></div></div><dl class="detail-metrics"><div v-for="([key,value],index) in metrics" :key="key"><b>{{ index+1 }}</b><dt>{{ key }}</dt><dd>{{ value }}</dd></div></dl></header>
    <section class="detail-panel"><h2>应用基本信息</h2><dl class="info-grid work-info"><div><dt>版本号</dt><dd>海能work应用</dd></div><div><dt>应用编码</dt><dd>HAINENG-WORK-001</dd></div><div><dt>所属场景</dt><dd>供应链管理</dd></div><div><dt>应用描述</dt><dd>集成海油核心业务应用，统一工作门户，提升协同效率。</dd></div><div class="video-cell"><dt>应用图片或视频</dt><dd><img src="/assets/work-video.png" width="240" height="92" alt="海能work应用演示视频封面" /></dd></div></dl></section>
    <section class="detail-panel"><h2>使用指南</h2><dl class="info-grid"><div><dt>使用功能</dt><dd>多租表格</dd></div><div><dt>使用说明</dt><dd><a href="#main-content">查看使用说明文档</a></dd></div></dl></section>
    <section class="detail-panel"><h2>相关培训内容</h2><table class="file-list"><tbody><tr v-for="(name,index) in ['海能work应用功能介绍','海能work应用使用入门','海能work应用高级技巧','海能work应用常见问题解析']" :key="name"><td><img src="/assets/work-logo.png" width="52" height="24" alt="" /></td><td>{{ name }}</td><td>视频　·　{{ 12+index }}:40</td><td><a href="/training">去学习</a></td></tr></tbody></table></section>
    <section class="detail-panel"><h2>关联素材</h2><div class="related-row"><article v-for="(item,index) in ['通用行业知识流程数据集','文本摘要RPA脚本','智能办公数据看板']" :key="item"><img :src="['/assets/app-dataset.png','/assets/app-rpa.png','/assets/app-cockpit.png'][index]" alt="" /><div><h3>{{ item }}</h3><p>{{ 1275+index*1065 }} 次下载</p></div></article></div></section>
    <form class="detail-comment" @submit.prevent><label>应用评论<input placeholder="请输入您对该应用的评论..." /></label><button type="submit">提交评论</button></form>
  </article>
</template>
<style scoped>.work-detail .detail-hero{min-height:220px}.video-cell{grid-column:1/-1}.work-info .video-cell dd{padding:8px}.work-info .video-cell img{width:240px;height:92px;object-fit:cover}a{color:#0870e8}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}</style>
