<script setup>
import { computed, reactive } from 'vue';
import PaginationControl from '../components/PaginationControl.vue';
// Reference SHA-256: 82F80F3AB4A821165E6B14344C809B5E102CC7DD8013DD69B7F7F39BF9900F34
const props=defineProps({integrationData:{type:Object,default:null},integrationState:{type:String,default:'mock'}});
const fallbackRows=[['JF202505060001','应用建设','应用正式上架：供应商评估看板','+30','2,850','2025-05-06 10:18:25','项目经理，应用首次正式上架'],['JF202505060002','应用互动','发布有效应用评论：供应商风险预警','+2','2,820','2025-05-06 09:32:11','同一应用当月首次有效评论'],['JF202505050001','应用使用','使用申请审批通过：AI采购应用实践','+3','2,818','2025-05-05 16:45:32','每个应用首次审批通过'],['JF202505050002','应用互动','首次收藏应用：采购异常预警','+2','2,815','2025-05-05 15:22:07','同一应用首次收藏'],['JF202505040001','培训学习','首次点击课程学习链接：供应链分析','+3','2,813','2025-05-04 11:03:44','每门课程首次'],['JF202505030001','基础活跃','每日首次进入数智展厅','+2','2,810','2025-05-03 14:18:55','每日1次'],['JF202505020001','培训学习','首次查看课程详情：采购数字化实践','+1','2,808','2025-05-02 10:05:18','每门课程1次'],['JF202505010001','应用使用','提交应用使用申请：增值税发票查验机器人','+2','2,807','2025-05-01 17:20:36','每个应用首次提交']];
const state=reactive({type:'',source:'',keyword:'',page:1,pageSize:10,announcement:''});
const remote=computed(()=>props.integrationData?.['PTS-002']);
const remoteMode=computed(()=>Array.isArray(remote.value?.items));
const rows=computed(()=>remoteMode.value?remote.value.items.map(item=>[
  item.serialNo,item.pointTypeName||item.pointTypeCode,item.sourceName||item.sourceCode,
  `${item.changePoints>=0?'+':''}${item.changePoints}`,Number(item.balanceAfter||0).toLocaleString('zh-CN'),
  item.occurredAt?.replace('T',' ').slice(0,19)||'',item.remark,item.statusName||item.statusCode
]):fallbackRows.map(item=>[...item,'已生效']));
const filtered=computed(()=>rows.value.filter(row=>(!state.type||row[1]===state.type)&&(!state.source||row[2]===state.source)&&(!state.keyword||`${row[0]} ${row[6]}`.toLocaleLowerCase('zh-CN').includes(state.keyword.toLocaleLowerCase('zh-CN')))));
const paged=computed(()=>{const start=(state.page-1)*state.pageSize;return filtered.value.slice(start,start+state.pageSize);});
const types=computed(()=>[...new Set(rows.value.map(row=>row[1]).filter(Boolean))]);
const sources=computed(()=>[...new Set(rows.value.map(row=>row[2]).filter(Boolean))]);
const summary=computed(()=>remote.value?.summary||{income:320,expense:0,netChange:320});
function reset(){Object.assign(state,{type:'',source:'',keyword:'',page:1,announcement:'已重置积分筛选'});}
function submit(){state.page=1;state.announcement=`查询完成，共 ${filtered.value.length} 条积分流水`;}
function setPage(value){const pages=Math.max(1,Math.ceil(filtered.value.length/state.pageSize));state.page=Math.min(pages,Math.max(1,Number(value)||1));}
function setPageSize(value){state.pageSize=[10,20,50].includes(Number(value))?Number(value):10;state.page=1;}
</script>
<template><article class="points-details" aria-labelledby="point-detail-title"><p class="sr-only" aria-live="polite">{{ state.announcement }}</p><nav aria-label="面包屑">我的首页　/　积分中心　/　积分明细</nav><header><h1 id="point-detail-title">积分明细</h1><p>查看积分获得与变动记录</p></header><section class="detail-stats"><article v-for="(stat,index) in [['本页收入',summary.income],['本页支出',summary.expense],['净变动',summary.netChange]]" :key="stat[0]"><AppIcon :name="['points-current','points-month','points-use'][index]" :size="60" /><div><small>{{ stat[0] }}</small><strong>{{ Number(stat[1]||0).toLocaleString('zh-CN') }}</strong></div></article></section><form class="point-filter" @submit.prevent="submit" @reset.prevent="reset"><label>积分类型<select v-model="state.type"><option value="">全部</option><option v-for="value in types" :key="value">{{ value }}</option></select></label><label>来源场景<select v-model="state.source"><option value="">全部</option><option v-for="value in sources" :key="value">{{ value }}</option></select></label><label>时间范围<input disabled placeholder="当前已加载结果"/></label><label>关键字<input v-model="state.keyword" placeholder="请输入流水号/备注关键字"/></label><button type="reset">重置</button><button type="submit">查询</button></form><nav class="point-tabs" aria-label="积分分类"><button type="button" aria-current="page">全部（{{ filtered.length }}）</button><button v-for="value in types" :key="value" type="button" @click="state.type=value;state.page=1">{{ value }}</button><button type="button" disabled title="真实导出写操作尚未开放">导出明细</button></nav><section class="point-table"><table><thead><tr><th>流水号</th><th>积分类型</th><th>来源场景</th><th>积分变化</th><th>变动后余额</th><th>时间</th><th>状态</th><th>备注</th></tr></thead><tbody><tr v-for="row in paged" :key="row[0]"><td>{{ row[0] }}</td><td><mark>{{ row[1] }}</mark></td><td>{{ row[2] }}</td><td class="green">{{ row[3] }}</td><td>{{ row[4] }}</td><td>{{ row[5] }}</td><td><span class="active">{{ row[7] }}</span></td><td>{{ row[6] }}</td></tr></tbody></table><p v-if="!filtered.length" class="point-empty" role="status">暂无符合条件的积分流水</p><PaginationControl :total="filtered.length" :page="state.page" :page-size="state.pageSize" label="积分流水分页" @update:page="setPage" @update:page-size="setPageSize" /></section></article></template>
<style scoped>.points-details{padding:17px 24px;color:#17304f}.points-details>nav{color:#60758d;font-size:11px}.points-details h1{margin:22px 0 5px;font-size:25px}.points-details>header p{color:#60758d;font-size:12px}.detail-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:22px;margin:14px 0 18px}.detail-stats article{height:106px;display:flex;align-items:center;gap:25px;padding:20px;background:#fff;border:1px solid #dce5ef;border-radius:6px}.detail-stats img{width:65px;height:65px}.detail-stats small{display:block;font-size:12px}.detail-stats strong{display:block;margin-top:8px;font-size:27px}.point-filter{display:grid;grid-template-columns:repeat(4,1fr) auto auto;gap:18px;padding:15px 18px;background:#fff;border:1px solid #dce5ef;border-radius:6px}.point-filter label{display:flex;align-items:center;gap:10px;font-size:11px}.point-filter input,.point-filter select{height:34px;min-width:0;flex:1;padding:0 10px;border:1px solid #d8e2ec}.point-filter button{height:34px;padding:0 20px;color:#0870e8;background:#fff;border:1px solid #0870e8;border-radius:4px}.point-filter button:last-child{color:#fff;background:#0870e8}.point-tabs{display:flex;gap:37px;align-items:center;height:50px}.point-tabs button{height:100%;border:0;color:#1a3150;background:transparent}.point-tabs button[aria-current=page]{color:#0870e8;border-bottom:3px solid #0870e8}.point-tabs button:last-child{margin-left:auto;height:34px;border:1px solid #0870e8}.point-table{background:#fff;border:1px solid #dce5ef;border-radius:6px}.point-table table{width:100%;border-collapse:collapse;font-size:10px}.point-table th,.point-table td{height:41px;padding:0 15px;border-bottom:1px solid #e1e8ef;text-align:left}.point-table th{background:#f6f8fb}.point-table mark{color:#0870e8;background:#e9f3ff}.green{color:#09a35a}.active{color:#159354}.point-table footer{display:flex;justify-content:space-between;padding:16px}.point-table footer button{height:32px;padding:0 12px;border:1px solid #d4dfea;background:#fff}.point-table footer button[aria-current=page]{color:#fff;background:#0870e8}button:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}@media(max-width:900px){.point-filter{grid-template-columns:1fr 1fr}.point-table{overflow:auto}.point-table table{min-width:1000px}}
.point-empty{padding:42px;text-align:center;color:#60718a}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}</style>
