<script setup>
// Reference SHA-256: 0750EA98D775041275D2A2308F5B33A01EEA9BB3EA37ACFADEDAA71755820887
import { computed, nextTick, ref } from 'vue';
import { createDetailController } from '../state/detail-controller.js';
import { routeSession } from '../state/session-store.js';
const metrics=[['应用评分/分数','4.9/5.0 ☆'],['应用类型','可视化报表'],['专业领域','经营分析'],['最近更新时间','2025-05-16'],['开发部门/单位','数智运营部'],['开发者','李四强'],['使用部门','各经营单位'],['开通范围','全部']];
const features=[['数据查询','按时间维度、经营维度、生产维度、区域维度、统计维度分析'],['经营指标看板','经营 EVA 仪表盘'],['指标趋势分析','支持同比/环比、趋势对比、历史走势及预测趋势分析'],['图表可视化','柱状图、折线图、饼图、地图等多种可视化图表'],['数据导出与分享','支持导出 PDF/Excel 图片/分享链接等多种方式'],['权限与安全','支持数据权限控制与操作日志审计']];
const props=defineProps({integrationData:{type:Object,default:null},integrationState:{type:String,default:'mock'},operationExecutor:{type:Function,default:null}});
const fallbackAttachments=['用户操作手册.pdf','快速使用指南.pdf','经营指标口径说明.xlsx','报表数据接口规范.docx'];
const attachments=computed(()=>props.integrationData?.['APP-003']?.attachments?.length?props.integrationData['APP-003'].attachments:fallbackAttachments.map((name,index)=>({attachmentId:'',name,sizeBytes:Math.round((2.8-index*.4)*1024*1024),uploadedAt:`2025-05-${String(10-index*2).padStart(2,'0')} 09:20`,uploadedBy:'李四强'})));
const training=['可视化报表功能介绍','图表配置与数据筛选','多维分析与联动钻取','报表导出与分享'];
const related=[['经营分析报表模板','/apps/tool-001','/assets/report-logo.png'],['经营指标数据集','/apps/dataset-001','/assets/app-dataset.png'],['月度经营分析指标','/apps/metric-001','/assets/app-metric.png']];
const detail=routeSession.controller('detail-report',()=>createDetailController('/apps/report-001',routeSession,{name:'经营分析可视化报表'}));
const commentInput=ref(null);
async function submitComment(){if(detail.submitComment()){await nextTick();commentInput.value?.focus();}}
async function downloadAttachment(file){
  if(!file.attachmentId||!props.operationExecutor||props.integrationState==='mock'){detail.mockDownload(file.name);return;}
  detail.announcement=`${file.name}：正在准备下载`;
  try{
    const response=await props.operationExecutor('COM-008',{fileId:file.attachmentId,mode:'DOWNLOAD',disposition:'ATTACHMENT',fileNameOverride:file.name});
    window.location.assign(response.data.url);
  }catch(error){
    if(error?.status===401){window.location.assign(`/api/v1/auth/feishu/start?returnTo=${encodeURIComponent(window.location.pathname)}`);return;}
    detail.announcement=`${file.name}：下载失败，请稍后重试`;
  }
}
</script>
<template>
  <article class="product-detail report-detail" data-visual-baseline="ui-update-0831-report" aria-labelledby="report-title"><p class="sr-only" aria-live="polite">{{ detail.announcement }}</p><nav class="detail-crumb" aria-label="面包屑"><span><a href="/apps" data-detail-return>应用中心</a>　›　专业应用　›　经营分析　›　经营分析可视化报表</span><button type="button" @click="detail.apply('浏览量统计')">浏览量统计</button></nav>
    <header class="detail-hero"><div class="detail-hero-main"><AppIcon class="detail-logo" name="report-logo" :size="80" label="经营分析可视化报表图标" /><div class="detail-title"><h1 id="report-title">经营分析可视化报表</h1><p>汇聚企业经营核心数据，通过多维数据驾驶舱与智能分析模型，直观呈现经营指标，辅助科学决策。</p><p>支持多维度查询，图表可视化展示与导出，便于经营人员快速识别问题、洞察趋势并制定行动方案。</p><div class="detail-tags"><strong>所属URL地址</strong><b>本地受控演示</b></div><div class="detail-tags"><strong>应用类型</strong><mark>经营分析</mark><mark>可视化报表</mark><mark>数据查询</mark><mark>经营优化</mark><mark>多维分析</mark></div></div><div class="detail-hero-side"><div><button type="button" :aria-pressed="detail.favorite" @click="detail.toggleFavorite">{{ detail.favorite?'已收藏':'收藏' }}</button><button type="button" @click="detail.apply('申请使用')">申请使用</button><button type="button" @click="detail.apply('联系部门')">联系部门</button></div><img class="detail-illustration" src="/assets/report-hero.png" width="220" height="160" alt="可视化报表插画" /></div></div></header>
    <dl class="detail-metrics"><div v-for="([key,value],index) in metrics" :key="key"><b>{{ index+1 }}</b><dt>{{ key }}</dt><dd>{{ value }}</dd></div></dl>
    <div class="detail-two-column"><section class="detail-panel"><h2>应用简介</h2><dl class="info-list"><div><dt>应用编码</dt><dd>APP-CPJFXB-001</dd></div><div><dt>版本号</dt><dd>V2.0.0</dd></div><div><dt>所属系统</dt><dd>浏览器</dd></div><div><dt>兼容环境</dt><dd>Windows 7、Chrome 98、推荐更高</dd></div><div><dt>数据来源</dt><dd>集团统一经营数据库、ERP、生产系统、财务系统等</dd></div><div><dt>更新频率</dt><dd>每日更新</dd></div><div><dt>应用简介</dt><dd>汇聚、整合、可视化经营数据，赋能管理决策</dd></div></dl></section>
    <section class="detail-panel"><h2>核心功能</h2><div class="feature-list"><article v-for="([name,text]) in features" :key="name"><strong>{{ name }}</strong><p>{{ text }}</p></article></div></section></div>
    <section class="detail-panel"><h2>演示截图</h2><figure><img class="preview-wide" src="/assets/report-previews.png" width="640" height="195" alt="" /><figcaption>经营指标总览、趋势分析与结构分布三项只读报表预览；当前演示不连接真实经营数据。</figcaption></figure></section>
    <div class="detail-two-column lower"><section class="detail-panel usage-panel"><h2>使用说明 <a href="/apps">查看使用手册</a></h2><div class="related-row"><article><b>PDF</b><div><h3>经营分析可视化报表-用户操作手册.pdf</h3><p>2.4 MB　2025-04-20</p></div></article><article><b>PDF</b><div><h3>经营分析可视化报表-数据说明文档.pdf</h3><p>2.1 MB　2025-04-18</p></div></article></div></section>
    <section class="detail-panel"><h2>附件资料 <span>查看全部({{ attachments.length }})</span></h2><table class="file-list"><caption class="sr-only">经营分析可视化报表附件资料</caption><thead><tr><th scope="col">文件名称</th><th scope="col">大小(MB)</th><th scope="col">上传时间</th><th scope="col">上传人</th><th scope="col">操作</th></tr></thead><tbody><tr v-for="file in attachments" :key="file.attachmentId||file.name"><td>{{ file.name }}</td><td>{{ (file.sizeBytes/1024/1024).toFixed(2) }} MB</td><td>{{ file.uploadedAt }}</td><td>{{ file.uploadedBy }}</td><td><button class="text-action" type="button" @click="downloadAttachment(file)">下载</button></td></tr></tbody></table></section></div>
    <div class="detail-two-column bottom"><section class="detail-panel"><h2>相关培训内容 <a href="/training">查看全部(4)</a></h2><div class="training-row"><article v-for="(name,index) in training.slice(0,3)" :key="name"><div><h3>{{ name }}</h3><p>时长：{{ 14+index*2 }}:30</p><a href="/training" :aria-label="`学习：${name}`">观看视频</a></div></article></div></section>
    <section class="detail-panel"><h2>关联素材 <span>查看全部(4)</span></h2><div class="related-row"><article v-for="([name,route,image],index) in related" :key="name"><AppIcon :name="image" :size="48" /><div><h3><a :href="route">{{ name }}</a></h3><p>{{ 2.6+index*1.2 }} MB</p><a :href="route">查看素材</a></div></article></div></section></div>
    <form class="detail-comment" @submit.prevent="submitComment"><label>应用评论<input ref="commentInput" v-model="detail.commentDraft" placeholder="请输入您对该应用的评论..." /></label><button type="submit" :disabled="!detail.commentDraft.trim()">提交评论</button><ul v-if="detail.comments.length" aria-label="本地评论"><li v-for="comment in detail.comments" :key="comment.id" :data-comment-id="comment.id">{{ comment.text }}</li></ul></form>
  </article>
</template>
<style scoped>
.report-detail{min-height:1428px;padding:0 13px 20px;color:#132d51;background:#fff}.detail-crumb{height:51px;display:flex;align-items:center;justify-content:space-between;padding:0 8px;color:#17385f;font-size:11px}.detail-crumb button{height:28px;padding:0 12px;color:#17385f;background:#fff;border:1px solid #cfdae7;border-radius:4px}
.report-detail .detail-hero{min-height:264px;padding:27px 31px 20px;border-color:#dce4ed;background:#fff}.report-detail .detail-hero-main{grid-template-columns:82px minmax(0,1fr) 275px;gap:24px}.report-detail .detail-logo{width:80px;height:80px;padding:16px;border:1px solid #dce5ef;border-radius:6px}.report-detail .detail-title h1{display:block;margin:0 0 8px;font-size:20px}.report-detail .detail-title>p{margin:0 0 5px;color:#324f70;font-size:10px;line-height:1.8}.report-detail .detail-tags{position:static;display:flex;margin-top:13px;gap:9px}.report-detail .detail-tags strong{width:88px}.report-detail .detail-tags b{color:#075fc0}.report-detail .detail-tags mark{margin:0;padding:4px 10px;color:#128067;background:#e6f6f0}.report-detail .detail-hero-side>div{display:flex;justify-content:flex-end;gap:13px}.report-detail .detail-hero-side button{height:31px;min-width:74px;padding:0 12px}.report-detail .detail-illustration{width:240px;height:145px;margin:17px 0 0 auto}
.report-detail>.detail-metrics{position:static;display:grid;grid-template-columns:repeat(8,1fr);min-height:87px;margin:10px 0 0;padding:12px 7px;background:#fff;border:1px solid #dce4ed;border-radius:6px}.report-detail>.detail-metrics div{min-height:55px;display:grid;grid-template-columns:22px 1fr;padding:0 9px}.report-detail>.detail-metrics b{width:18px;height:18px}.report-detail>.detail-metrics dt{font-size:9px}.report-detail>.detail-metrics dd{font-size:10px;font-weight:700}
.detail-two-column{display:grid;grid-template-columns:1fr 1.07fr;gap:10px}.report-detail .detail-panel{margin-top:10px;padding:14px 18px;border-color:#dce4ed;background:#fff}.report-detail .detail-panel>h2{margin-bottom:13px;font-size:13px}.report-detail .detail-panel>h2::before{display:none}.report-detail .detail-panel>h2 :is(a,span){margin-left:auto;color:#075fc0;font-size:9px;font-weight:400}.info-list{display:grid;gap:9px;margin:0}.info-list div{display:grid;grid-template-columns:95px 1fr;font-size:9px}.info-list dt{font-weight:700}.info-list dd{margin:0;color:#405a77}.feature-list{display:grid;gap:8px}.feature-list article{display:grid;grid-template-columns:95px 1fr;font-size:9px}.feature-list strong::before,.info-list dt::before{content:'';display:inline-block;width:4px;height:4px;margin:0 10px 2px 0;background:#075fc0;border-radius:50%}.feature-list p{color:#405a77}
.report-detail figure{margin:0}.report-detail .preview-wide{width:100%;height:205px;object-fit:cover;border-radius:4px}.report-detail figcaption{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.lower{grid-template-columns:.82fr 1.18fr}.bottom{grid-template-columns:.82fr 1.18fr}.report-detail .usage-panel .related-row{grid-template-columns:1fr}.report-detail .usage-panel .related-row article{min-height:55px}.report-detail .usage-panel .related-row b{width:28px;height:28px;display:grid;place-items:center;color:#fff;background:#e51e2a;border-radius:4px;font-size:8px}.report-detail .file-list{font-size:8px}.report-detail .file-list th,.report-detail .file-list td{height:23px;padding:0 6px}.report-detail .training-row{grid-template-columns:repeat(3,1fr);gap:9px}.report-detail .training-row article{min-height:74px;align-items:flex-start}.report-detail .related-row{grid-template-columns:repeat(3,1fr);gap:9px}.report-detail .related-row article{min-height:75px}.report-detail .related-row img{display:none}.report-detail .training-row h3,.report-detail .related-row h3{font-size:9px}.report-detail .training-row a,.report-detail .related-row a{color:#075fc0;font-size:8px}
.report-detail .detail-comment{position:static;min-height:63px;margin-top:10px;padding:12px 18px;border-color:#dce4ed;background:#fff}.report-detail .detail-comment label{font-size:12px}.report-detail .detail-comment input{height:32px}.report-detail .detail-comment button{min-width:78px;background:#003d7b}.report-detail .detail-title>p:nth-of-type(2){position:static}.text-action{padding:0;border:0;color:#075fc0;background:transparent}.detail-comment ul{margin:12px 0 0;padding-left:24px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}button:focus-visible,a:focus-visible{outline:3px solid #1b77d2;outline-offset:2px}
</style>
