<script setup>
// Reference SHA-256: 1C66525AC285F0825E52CEB928093EB0CA7A412C4B526B51E181A5A16BC732C3
import { computed } from 'vue';
import PaginationControl from '../components/PaginationControl.vue';
import { PROGRESS_DOCUMENT_COLUMNS, PROGRESS_FIXTURES, createTalentProgressController } from '../state/talent-progress-controller.js';
const controller=createTalentProgressController(PROGRESS_FIXTURES);
const options=key=>computed(()=>[...new Set(PROGRESS_FIXTURES.map(project=>project[key]))]);
const progressOptions=options('progress');const domainOptions=options('domain');const stageOptions=options('stage');const statusOptions=options('status');
</script>
<template><article class="progress-page" aria-labelledby="progress-title"><p class="sr-only" aria-live="polite">{{ controller.announcement }}</p><nav>人才管理　/　项目进度管理</nav><section><header><h1 id="progress-title">项目进度管理</h1><p>查看和管理您所负责的所有人才培养项目的进度情况。</p></header><form @submit.prevent="controller.submit" @reset.prevent="controller.reset"><input :value="controller.draft.query" aria-label="项目关键词" placeholder="请输入项目名称或编号" @input="controller.draft.query=$event.target.value"/><label>项目进度<select :value="controller.draft.progress" @change="controller.draft.progress=$event.target.value"><option value="">全部</option><option v-for="value in progressOptions" :key="value">{{ value }}</option></select></label><label>业务领域<select :value="controller.draft.domain" @change="controller.draft.domain=$event.target.value"><option value="">全部</option><option v-for="value in domainOptions" :key="value">{{ value }}</option></select></label><label>当前阶段<select :value="controller.draft.stage" @change="controller.draft.stage=$event.target.value"><option value="">全部</option><option v-for="value in stageOptions" :key="value">{{ value }}</option></select></label><label>项目状态<select :value="controller.draft.status" @change="controller.draft.status=$event.target.value"><option value="">全部</option><option v-for="value in statusOptions" :key="value">{{ value }}</option></select></label><button type="submit">查询</button><button type="reset">重置</button><button type="button" disabled title="本地演示不生成导出文件">导出</button></form><div class="progress-table horizontal-scroll-region" tabindex="0" role="region" aria-label="项目进度管理列表，可左右滚动"><table><caption class="sr-only">项目进度管理列表</caption><thead><tr><th scope="col">项目编号</th><th scope="col">项目名称</th><th scope="col">项目进度(阶段)</th><th scope="col">预计/已完成日期</th><th scope="col">规模等级</th><th scope="col">智能运营部门评分</th><th scope="col">当前项目节点</th><th scope="col">里程碑日期</th><th v-for="label in PROGRESS_DOCUMENT_COLUMNS" :key="label" scope="col">{{ label }}</th><th scope="col">操作</th></tr></thead><tbody><tr v-for="project in controller.pagedResults" :key="project.id"><td>{{ project.id }}</td><td>{{ project.name }}</td><td>{{ project.progress }}</td><td>{{ project.date }}</td><td>{{ project.scale }}</td><td>{{ project.score }}</td><td>{{ project.stage }}</td><td>{{ project.milestone }}</td><td v-for="label in PROGRESS_DOCUMENT_COLUMNS" :key="label"><button v-if="project.documents[label]===1" type="button" :aria-label="`${project.name} ${label}`" @click="controller.explainDocument(project,label)">文档</button><span v-else>{{ project.documents[label] }}</span></td><td><button type="button" :aria-label="`查看 ${project.name} 详情`" @click="controller.explainDetail(project)">查看详情</button></td></tr></tbody></table></div><PaginationControl :total="controller.results.length" :page="controller.page" :page-size="controller.pageSize" label="项目进度分页" @update:page="controller.setPage" @update:page-size="controller.setPageSize" /></section></article></template>
<style scoped>.progress-page{padding:12px 18px;color:#17304f}.progress-page>nav{font-size:10px}.progress-page>section{margin-top:12px;padding:20px;background:#fff;border:1px solid #f4faff;border-radius:6px}.progress-page h1{margin:0;font-size:24px}.progress-page header p{margin-top:6px;font-size:10px}.progress-page form{display:grid;grid-template-columns:224px repeat(4,128px) repeat(3,68px);gap:16px;margin:28px 0}.progress-page form input,.progress-page form select,.progress-page form button{height:36px;border:1px solid #f4faff;font-size:14px}.progress-page form label{display:flex;align-items:center;gap:5px;font-size:14px}.progress-page form button:last-child{color:#8794a4;background:#f2f4f7}.progress-table{overflow:auto;border:1px solid #f4faff}.progress-page table{width:100%;min-width:1640px;border-collapse:collapse;font-size:13px;line-height:20px}.progress-page th,.progress-page td{padding:0 16px;border-bottom:1px solid #f4faff;text-align:center}.progress-page th{height:60px;font-weight:600;background:#f5f7fa}.progress-page td{height:67px;font-weight:400}.progress-page td:nth-child(2){text-align:left;font-size:13px}.progress-page td button{padding:0;color:#0870e8;background:transparent;border:0}.sr-only{position:absolute;width:1px;height:1px;margin:-1px;overflow:hidden;clip:rect(0,0,0,0)}button:focus-visible,a:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}@media(max-width:1054px){.progress-page,.progress-page>section{min-width:0;max-width:100%}.progress-page form{width:100%;max-width:100%;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px 16px}.progress-page form label,.progress-page form input,.progress-page form select,.progress-page form button{width:100%;min-width:0}.progress-table{width:100%;min-width:0;max-width:100%;overflow-x:auto}.progress-page :deep(.pagination-control){min-width:0;max-width:100%;flex-wrap:wrap}}</style>
