<script setup>
// Reference SHA-256: 1C66525AC285F0825E52CEB928093EB0CA7A412C4B526B51E181A5A16BC732C3
import { computed, ref } from 'vue';
import PaginationControl from '../components/PaginationControl.vue';
const rows=[['PRJ20250608001','海上平台数字化人才培养项目','进行中','2025-08-31','中等','85','方案设计','2025-05-30','有','有','有','有','有','--','--','85分'],['PRJ20250607002','数据分析人才提升计划','已完成','2025-06-30','中型','95','项目完成','2025-06-30','有','有','有','有','有','--','--','--'],['PRJ20250606003','AI应用开发人才储备项目','进行中','2025-09-20','大型','80','开发实施','2025-06-15','有','有','有','有','有','--','--','80分'],['PRJ20250605004','管理人才梯队建设项目','进行中','2025-10-31','中等','75','需求分析','2025-06-10','有','有','有','有','有','--','--','--'],['PRJ20250604005','专业技术人才培养计划','进行中','2025-08-15','大型','88','开发实施','2025-06-05','有','有','有','有','有','--','--','--'],['PRJ20250603006','国际化人才培养项目','暂停中','2025-07-31','大型','70','测试验证','2025-05-20','有','有','有','有','有','--','--','--'],['PRJ20250602007','青年人才成长计划','未开始','2025-11-30','中型','--','项目启动','--','--','--','--','--','--','--','--','--'],['PRJ20250601008','技能提升培训项目','未开始','2025-09-30','中等','--','项目启动','--','--','--','--','--','--','--','--','--']];
const page=ref(1);const pageSize=ref(10);const pagedRows=computed(()=>rows.slice((page.value-1)*pageSize.value,page.value*pageSize.value));
function setPage(value){page.value=Math.min(Math.max(1,Number(value)||1),Math.max(1,Math.ceil(rows.length/pageSize.value)));}
function setPageSize(value){pageSize.value=Number(value)||10;page.value=1;}
</script>
<template><article class="progress-page" aria-labelledby="progress-title"><nav>人才管理　/　项目进度管理</nav><section><header><h1 id="progress-title">项目进度管理</h1><p>查看和管理您所负责的所有人才培养项目的进度情况。</p></header><form @submit.prevent><input aria-label="项目关键词" placeholder="请输入项目名称或编号"/><label>项目进度<select><option>全部</option></select></label><label>业务领域<select><option>全部</option></select></label><label>当前阶段<select><option>全部</option></select></label><label>项目状态<select><option>全部</option></select></label><button type="reset">重置</button><button type="button" disabled title="本地演示不生成导出文件">导出</button></form><div class="progress-table"><table><caption class="sr-only">项目进度管理列表</caption><thead><tr><th scope="col">项目编号</th><th scope="col">项目名称</th><th scope="col">项目进度(阶段)</th><th scope="col">预计/已完成日期</th><th scope="col">规模等级</th><th scope="col">智能运营部门评分</th><th scope="col">当前项目节点</th><th scope="col">里程碑日期</th><th scope="col">工作计划书</th><th scope="col">需求问卷</th><th scope="col">需求说明</th><th scope="col">蓝图报告</th><th scope="col">蓝图评审意见</th><th scope="col">验收材料</th><th scope="col">交付物</th><th scope="col">验收意见</th><th scope="col">操作</th></tr></thead><tbody><tr v-for="row in pagedRows" :key="row[0]"><td v-for="(value,index) in row" :key="`${index}-${value}`"><a v-if="value==='有'" href="#main-content" aria-label="查看文档">文档</a><span v-else>{{ value }}</span></td><td><a href="#main-content">查看详情</a></td></tr></tbody></table><PaginationControl :total="rows.length" :page="page" :page-size="pageSize" label="项目进度分页" @update:page="setPage" @update:page-size="setPageSize" /></div></section></article></template>
<style scoped>.progress-page{padding:12px 18px;color:#17304f}.progress-page>nav{font-size:10px}.progress-page>section{margin-top:12px;padding:20px;background:#fff;border:1px solid #f4faff;border-radius:6px}.progress-page h1{margin:0;font-size:24px}.progress-page header p{margin-top:6px;font-size:10px}.progress-page form{display:grid;grid-template-columns:224px repeat(4,128px) 68px 68px;gap:16px;margin:28px 0}.progress-page form input,.progress-page form select,.progress-page form button{height:36px;border:1px solid #f4faff;font-size:14px}.progress-page form label{display:flex;align-items:center;gap:5px;font-size:14px}.progress-page form button:last-child{color:#8794a4;background:#f2f4f7}.progress-table{overflow:auto;border:1px solid #f4faff}.progress-page table{width:100%;min-width:1640px;border-collapse:collapse;font-size:13px;line-height:20px}.progress-page th,.progress-page td{padding:0 16px;border-bottom:1px solid #f4faff;text-align:center}.progress-page th{height:60px;font-weight:600;background:#f5f7fa}.progress-page td{height:67px;font-weight:400}.progress-page td:nth-child(2){text-align:left;font-size:13px}.progress-page td a{color:#0870e8}.sr-only{position:absolute;width:1px;height:1px;margin:-1px;overflow:hidden;clip:rect(0,0,0,0)}button:focus-visible,a:focus-visible{outline:3px solid #ff9f1a;outline-offset:2px}</style>
