<script setup>
import { computed } from 'vue';
const props=defineProps({projection:{type:Object,required:true}});
const detail=computed(()=>props.projection.detail.value||props.projection.detail||{});
const sections=[['metrics','指标'],['features','核心功能'],['fieldDefinitions','字段定义'],['processSteps','流程步骤'],['previews','预览'],['videos','视频'],['attachments','附件'],['guides','使用指南'],['trainings','相关培训'],['relatedApps','相关应用'],['relatedMaterials','相关素材']];
const safeEntries=value=>value&&typeof value==='object'&&!Array.isArray(value)?Object.entries(value).filter(([,item])=>['string','number','boolean'].includes(typeof item)):[];
const safeText=item=>['string','number','boolean'].includes(typeof item)?String(item):safeEntries(item).map(([key,value])=>`${key}：${value}`).join('；');
</script>
<template><div v-if="projection.remoteMode" class="authoritative-detail-body"><section class="detail-panel"><h2>应用说明</h2><p>{{ detail.description || '暂无说明' }}</p></section><section v-for="([key,label]) in sections" :key="key" class="detail-panel"><h2>{{ label }}</h2><ul v-if="Array.isArray(detail[key])&&detail[key].length"><li v-for="(item,index) in detail[key]" :key="item.id||item.fileId||index">{{ safeText(item) || '—' }}</li></ul><p v-else>暂无{{ label }}</p></section><section class="detail-panel"><h2>类型扩展</h2><dl v-if="safeEntries(detail.typeExtension).length"><div v-for="([key,value]) in safeEntries(detail.typeExtension)" :key="key"><dt>{{ key }}</dt><dd>{{ value }}</dd></div></dl><p v-else>暂无类型扩展</p></section><section class="detail-panel"><h2>数据源摘要</h2><p>{{ safeText(detail.dataSourceSummary)||'暂无数据源摘要' }}</p></section><section class="detail-panel"><h2>最新公告</h2><p>{{ safeText(detail.latestNotice)||'暂无最新公告' }}</p></section></div></template>
<style scoped>.authoritative-detail-body{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.detail-panel{padding:18px;background:#fff;border:1px solid #dce5ef;border-radius:7px}.detail-panel h2{margin:0 0 10px;color:#173b60}.detail-panel p,.detail-panel li,.detail-panel dt,.detail-panel dd{line-height:1.65;color:#526b83}.detail-panel dl div{display:grid;grid-template-columns:minmax(120px,.35fr) 1fr;gap:10px}.detail-panel dd{margin:0}@media(max-width:900px){.authoritative-detail-body{grid-template-columns:1fr}}</style>
