import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { compileScript, parse } from '@vue/compiler-sfc';
import { createRenderer, nextTick } from 'vue';
import { launchApplication } from '../src/integration/application-actions.js';
const detailFiles=['AiDetailPage.vue','DashboardDetailPage.vue','DatasetDetailPage.vue','EadDetailPage.vue','HainengWorkDetailPage.vue','MetricDetailPage.vue','ToolDetailPage.vue','RpaDetailPage.vue','ReportDetailPage.vue'];
for(const file of detailFiles){const source=readFileSync(new URL(`../src/pages/${file}`,import.meta.url),'utf8');const hero=source.slice(source.indexOf('detail-hero-side'),source.indexOf('detail-hero-side')+1800);assert.match(hero,/v-if="!projection\.remoteMode"/,`${file} remote hero local actions must be hidden`);}
const source=readFileSync(new URL('../src/components/AppDetailLiveSections.vue',import.meta.url),'utf8');assert.match(source,/integrationState==='normal' && appId/);assert.match(source,/@click="launch"/);assert.doesNotMatch(source,/testWritesEnabled[^\n]*权限校验后使用/);
globalThis.window={location:{pathname:'/apps/report-001'},open:()=>{opened=true;}};globalThis.open=()=>{opened=true;};let opened=false;let calls=[];
const hostOps={createElement:type=>({type,props:{},children:[],addEventListener(){},removeEventListener(){},setAttribute(){}}),createText:text=>({type:'#text',text}),createComment:text=>({type:'#comment',text}),setText:(node,text)=>{node.text=text;},setElementText:(node,text)=>{node.text=text;node.children=[];},parentNode:node=>node.parent||null,nextSibling:()=>null,insert:(child,parent)=>{child.parent=parent;parent.children.push(child);},remove:child=>{if(child.parent)child.parent.children=child.parent.children.filter(node=>node!==child);},patchProp:(node,key,_old,value)=>{node.props[key]=value;},insertStaticContent:(content,parent)=>{const node={type:'#static',text:content,parent};parent.children.push(node);return[node,node];}};
const renderer=createRenderer(hostOps);const fileUrl=new URL('../src/components/AppDetailLiveSections.vue',import.meta.url);const parsed=parse(readFileSync(fileUrl,'utf8'),{filename:fileUrl.pathname});let code=compileScript(parsed.descriptor,{id:'detail-launch',inlineTemplate:true}).content;const vueUrl=new URL('../node_modules/vue/index.mjs',import.meta.url).href;code=code.replace(/from\s+(['"])vue\1/g,`from '${vueUrl}'`).replace(/from\s+(['"])(\.\.\/[^'"]+)\1/g,(_m,_q,relative)=>`from '${new URL(relative,fileUrl).href}'`);const Component=(await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`)).default;
const root={type:'root',children:[]};const executor=async(id,input)=>{calls.push({id,input});return {data:{allowed:true,launchUrl:'https://approved.example/app'}};};renderer.createApp(Component,{integrationState:'normal',integrationData:{'APP-003':{appId:'APP-REAL-001'}},operationExecutor:executor,testWritesEnabled:false}).mount(root);await nextTick();const all=node=>[node,...(node.children||[]).flatMap(all)];const launchButton=all(root).find(node=>node.type==='button'&&node.text==='权限校验后使用');assert.ok(launchButton,'remote normal must expose secure launch');launchButton.props.onClick();await nextTick();assert.equal(calls[0].id,'APP-004');assert.equal(opened,true);
assert.deepEqual(await launchApplication(async()=>({data:{allowed:false,reasonMessage:'无权限'}}),'APP-REAL-001'),{launched:false,message:'无权限'});
await assert.rejects(()=>launchApplication(async()=>{const error=new Error('unauthorized');error.status=401;throw error;},'APP-REAL-001'),/unauthorized/);
await assert.rejects(()=>launchApplication(executor,''),/缺少真实应用标识|真实应用启动接口/);
await assert.rejects(()=>launchApplication(async()=>{throw new Error('接口失败');},'APP-REAL-001'),/接口失败/);
console.log('详情 remote secure launch 与九页 hero 阻断合同通过');
