import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read=path=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const source=read('src/pages/ToolDetailPage.vue');
const live=read('src/components/AppDetailLiveSections.vue');
assert.match(source,/RemoteAppDetailPage/,'工具详情必须复用统一远端详情组件');
assert.match(source,/useAppDetailProjection/,'工具详情必须使用飞书远端投影');
assert.match(source,/icon="tools"/,'工具详情必须关联工具线稿图标');
for(const operation of ['APP-005','APP-006','APP-008','FAV-003','FAV-004'])assert.ok(live.includes(`'${operation}'`),`工具详情缺少 ${operation} 受控交互`);
assert.match(live,/v-if="testWritesEnabled"/,'详情写操作必须受 TEST_ 隔离开关控制');
assert.doesNotMatch(source,/本地演示|mockDownload|createDetailController/,'工具详情不得保留伪业务交互');
console.log('第六批 interaction：工具详情远端投影与受控真实操作合同通过');
