import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { compileScript, parse } from '@vue/compiler-sfc';
import { createRenderer, nextTick } from 'vue';
globalThis.window={location:{origin:'http://127.0.0.1:4173',href:'http://127.0.0.1:4173/operations/apps'}};
let requests=0;globalThis.fetch=()=>{requests+=1;throw new Error('admin list projection must not request directly');};
const flatten=node=>[node,...(node.children||[]).flatMap(flatten)];const textOf=node=>[node?.text||'',...(node?.children||[]).map(textOf)].join('');
const hostOps={createElement:type=>({type,props:{},children:[]}),createText:text=>({type:'#text',text}),createComment:text=>({type:'#comment',text}),setText:(node,text)=>{node.text=text;},setElementText:(node,text)=>{node.text=text;node.children=[];},parentNode:node=>node.parent||null,nextSibling:()=>null,insert:(child,parent)=>{child.parent=parent;parent.children.push(child);},remove:child=>{if(child.parent)child.parent.children=child.parent.children.filter(node=>node!==child);},patchProp:(node,key,_old,value)=>{node.props[key]=value;},insertStaticContent:(content,parent)=>{const node={type:'#static',text:content,parent};parent.children.push(node);return[node,node];}};
const renderer=createRenderer(hostOps);
async function load(path,id){const fileUrl=new URL(`../src/pages/${path}`,import.meta.url);const {descriptor,errors}=parse(readFileSync(fileUrl,'utf8'),{filename:fileUrl.pathname});assert.deepEqual(errors,[]);let code=compileScript(descriptor,{id,inlineTemplate:true}).content;const vueUrl=new URL('../node_modules/vue/index.mjs',import.meta.url).href;code=code.replace(/from\s+(['"])vue\1/g,`from '${vueUrl}'`).replace(/from\s+(['"])(\.\.\/[^'"]+)\1/g,(_m,_q,relative)=>`from '${new URL(relative,fileUrl).href}'`);return(await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`)).default;}
async function mount(component,props){const root={type:'root',children:[]};renderer.createApp(component,props).mount(root);await nextTick();return root;}
const Announcement=await load('AnnouncementAdminPage.vue','mounted-operation-announcements');const AppAdmin=await load('AppAdminPage.vue','mounted-operation-apps');
const annData={'OAN-001':{totalCount:1,publishedCount:1,draftCount:0,expiredCount:0},'OAN-002':{items:[{announcementId:'A-9',title:'权威运营公告',typeName:'平台通知',publishAt:'2026-09-11',scopeType:'ALL',statusName:'已发布',viewCount:19}],total:1,page:2,filtersApplied:{status:'PUBLISHED'}}};
const appData={'OAP-001':{totalCount:1,onlineCount:1,offlineCount:0,pendingCount:0},'OAP-002':{items:[{appId:'P-9',name:'权威运营应用',code:'APP-9',typeName:'AI',domainName:'采购',ownerName:'负责人甲',viewCount:21,userCount:8,statusName:'已上架',updatedAt:'2026-09-11'}],total:1,page:3,filtersApplied:{type:'AI'}},'OAP-011':{typeCode:'AI',usage:'DETAIL'}};
for(const [component,data,expected,fixture] of [[Announcement,annData,'权威运营公告','供应商风险预警应用已发布上线'],[AppAdmin,appData,'权威运营应用','物资采购管理系统']]){const root=await mount(component,{integrationState:'normal',integrationData:data});assert.match(textOf(root),new RegExp(expected));assert.doesNotMatch(textOf(root),new RegExp(fixture));const writes=flatten(root).filter(node=>node.type==='button'&&/新建|编辑|推荐|下线|删除/.test(textOf(node)));assert.ok(writes.length>0&&writes.every(node=>node.props.disabled!==undefined&&node.props.disabled!==false));for(const state of ['empty','error','permission-denied']){const stateRoot=await mount(component,{integrationState:state,integrationData:data});assert.doesNotMatch(textOf(stateRoot),new RegExp(`${expected}|${fixture}`));}const mock=await mount(component,{integrationState:'mock'});assert.match(textOf(mock),new RegExp(fixture));}
assert.equal(requests,0);console.log('真实运营列表 SFC mounted：remote 投影、状态隔离、mock 保留、写禁用与零请求通过');
