import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const certification=readFileSync(new URL('../src/pages/CertificationPage.vue',import.meta.url),'utf8');
const announcements=readFileSync(new URL('../src/pages/AnnouncementsPage.vue',import.meta.url),'utf8');
const editor=readFileSync(new URL('../src/pages/AnnouncementEditorPage.vue',import.meta.url),'utf8');
const admin=readFileSync(new URL('../src/pages/AdminPage.vue',import.meta.url),'utf8');
assert.match(certification,/remoteBookingBlocked/,'认证远程预约必须有独立阻断状态');
assert.match(certification,/预约服务尚未配置|正式预约写入合同尚未提供/,'认证阻断需给出明确文案');
assert.match(certification,/bookingDialog.*disabled|:disabled="remoteBookingBlocked"/s,'远程预约入口必须禁用');
assert.match(announcements,/publishConfigured|公告发布合同尚未配置/,'公告发布入口必须有配置门禁');
assert.match(editor,/remoteMode|publishConfigured/,'公告编辑页必须感知远程运行模式');
assert.match(editor,/保存草稿|预览|发布/,'公告编辑动作必须保留语义入口');
assert.match(editor,/v-model="draft\.title"/,'公告编辑页必须绑定可编辑的标题草稿');
assert.match(editor,/saveDraft|previewDraft|openAttachmentPicker/,'公告编辑页必须提供可见的草稿、预览和附件选择交互');
assert.match(editor,/仅保存在当前浏览器会话|正式公告发布合同尚未配置/,'公告编辑页必须明确本地草稿与正式发布的边界');
assert.match(admin,/topicDomainDialog|openTopicDomainDialog/,'后台主题域入口必须打开可见的交互面板');
assert.match(admin,/正式配置写入合同尚未提供|当前浏览器会话/,'后台主题域必须明确受控写入或本地会话边界');
console.log('remote certification and announcement write blocking contract passed');
