import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const certification=readFileSync(new URL('../src/pages/CertificationPage.vue',import.meta.url),'utf8');
const announcements=readFileSync(new URL('../src/pages/AnnouncementsPage.vue',import.meta.url),'utf8');
const editor=readFileSync(new URL('../src/pages/AnnouncementEditorPage.vue',import.meta.url),'utf8');
const admin=readFileSync(new URL('../src/pages/AdminPage.vue',import.meta.url),'utf8');
const matrix=readFileSync(new URL('../src/integration/page-integration-matrix.js',import.meta.url),'utf8');
assert.match(certification,/remoteBookingBlocked/,'认证远程预约必须有独立阻断状态');
assert.match(certification,/预约服务尚未配置|正式预约写入合同尚未提供/,'认证阻断需给出明确文案');
assert.match(certification,/bookingDialog.*disabled|:disabled="remoteBookingBlocked"/s,'远程预约入口必须禁用');
assert.match(announcements,/publishConfigured|公告发布合同尚未配置/,'公告发布入口必须有配置门禁');
assert.match(editor,/写入接口未启用时不提供草稿保存或发布/,'公告详情页必须明确禁用正式写入');
assert.match(editor,/<RemoteRecordPage/,'公告详情页只能展示服务端返回记录');
assert.doesNotMatch(editor,/v-model=|saveDraft|previewDraft|openAttachmentPicker/,'未配置写合同的公告页不得提供本地伪写入');
assert.match(admin,/<RemoteRecordPage/,'后台管理只能展示服务端返回记录');
assert.doesNotMatch(admin,/topicDomainDialog|openTopicDomainDialog/,'后台管理不得提供本地伪配置写入');
assert.match(matrix,/\/operations\/announcements\/notice-001\/edit[^\n]*'disabled'/,'公告管理写路由必须由集成矩阵禁用');
assert.match(matrix,/define\('26','\/admin'[^\n]*'disabled'/,'后台管理写动作必须由集成矩阵禁用');
console.log('remote certification and announcement write blocking contract passed');
